[2024-08-29T03:46:28.884+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-29T03:46:28.901+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: country_data_pipeline.load_data manual__2024-08-29T03:46:06.861900+00:00 [queued]>
[2024-08-29T03:46:28.913+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: country_data_pipeline.load_data manual__2024-08-29T03:46:06.861900+00:00 [queued]>
[2024-08-29T03:46:28.914+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-29T03:46:28.948+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): load_data> on 2024-08-29 03:46:06.861900+00:00
[2024-08-29T03:46:28.955+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=880) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-29T03:46:28.955+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'country_data_pipeline', 'load_data', 'manual__2024-08-29T03:46:06.861900+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/welcome_dags.py', '--cfg-path', '/tmp/tmpj2q_fdkf']
[2024-08-29T03:46:28.957+0000] {standard_task_runner.py:72} INFO - Started process 889 to run task
[2024-08-29T03:46:28.957+0000] {standard_task_runner.py:105} INFO - Job 186: Subtask load_data
[2024-08-29T03:46:29.026+0000] {task_command.py:467} INFO - Running <TaskInstance: country_data_pipeline.load_data manual__2024-08-29T03:46:06.861900+00:00 [running]> on host c63ae693b587
[2024-08-29T03:46:29.166+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='country_data_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-29T03:46:06.861900+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-29T03:46:06.861900+00:00'
[2024-08-29T03:46:29.168+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-29T03:46:30.090+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-08-29T03:46:30.118+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-29T03:46:30.119+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=country_data_pipeline, task_id=load_data, run_id=manual__2024-08-29T03:46:06.861900+00:00, execution_date=20240829T034606, start_date=20240829T034628, end_date=20240829T034630
[2024-08-29T03:46:30.222+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-29T03:46:30.253+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-29T03:46:30.257+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
