[2024-08-28T08:24:39.519+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-28T08:24:39.546+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: country_data_pipeline.load_data manual__2024-08-28T08:17:48.654498+00:00 [queued]>
[2024-08-28T08:24:39.564+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: country_data_pipeline.load_data manual__2024-08-28T08:17:48.654498+00:00 [queued]>
[2024-08-28T08:24:39.565+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-28T08:24:39.614+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): load_data> on 2024-08-28 08:17:48.654498+00:00
[2024-08-28T08:24:39.622+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=426) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-28T08:24:39.621+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'country_data_pipeline', 'load_data', 'manual__2024-08-28T08:17:48.654498+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/welcome_dags.py', '--cfg-path', '/tmp/tmpz73zde44']
[2024-08-28T08:24:39.623+0000] {standard_task_runner.py:72} INFO - Started process 435 to run task
[2024-08-28T08:24:39.624+0000] {standard_task_runner.py:105} INFO - Job 121: Subtask load_data
[2024-08-28T08:24:39.737+0000] {task_command.py:467} INFO - Running <TaskInstance: country_data_pipeline.load_data manual__2024-08-28T08:17:48.654498+00:00 [running]> on host c63ae693b587
[2024-08-28T08:24:39.913+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='country_data_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-28T08:17:48.654498+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-28T08:17:48.654498+00:00'
[2024-08-28T08:24:39.915+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-28T08:24:40.796+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-08-28T08:24:40.815+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-28T08:24:40.816+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=country_data_pipeline, task_id=load_data, run_id=manual__2024-08-28T08:17:48.654498+00:00, execution_date=20240828T081748, start_date=20240828T082439, end_date=20240828T082440
[2024-08-28T08:24:40.925+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-28T08:24:40.960+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-28T08:24:40.964+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
