[2024-08-28T03:16:19.536+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-28T03:16:19.565+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: country_data_pipeline.transform_data manual__2024-08-28T03:16:03.532787+00:00 [queued]>
[2024-08-28T03:16:19.586+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: country_data_pipeline.transform_data manual__2024-08-28T03:16:03.532787+00:00 [queued]>
[2024-08-28T03:16:19.587+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-28T03:16:19.645+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): transform_data> on 2024-08-28 03:16:03.532787+00:00
[2024-08-28T03:16:19.653+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'country_data_pipeline', 'transform_data', 'manual__2024-08-28T03:16:03.532787+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/welcome_dags.py', '--cfg-path', '/tmp/tmpelvvah55']
[2024-08-28T03:16:19.653+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=366) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-28T03:16:19.655+0000] {standard_task_runner.py:105} INFO - Job 42: Subtask transform_data
[2024-08-28T03:16:19.656+0000] {standard_task_runner.py:72} INFO - Started process 375 to run task
[2024-08-28T03:16:19.790+0000] {task_command.py:467} INFO - Running <TaskInstance: country_data_pipeline.transform_data manual__2024-08-28T03:16:03.532787+00:00 [running]> on host 1ba7238dfcc0
[2024-08-28T03:16:19.964+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='country_data_pipeline' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-28T03:16:03.532787+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-28T03:16:03.532787+00:00'
[2024-08-28T03:16:19.965+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-28T03:16:20.103+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-08-28T03:16:20.121+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-28T03:16:20.122+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=country_data_pipeline, task_id=transform_data, run_id=manual__2024-08-28T03:16:03.532787+00:00, execution_date=20240828T031603, start_date=20240828T031619, end_date=20240828T031620
[2024-08-28T03:16:20.194+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-28T03:16:20.237+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-28T03:16:20.261+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
